# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Azmyin Md. Kamal
name: Azmyin Md. Kamal
position: Graduate Research Assistant 
email: azmyin12@gmail.com
description: >-
  I am a robotics engineer currently working through a Ph.D. in Mechanical Engineering at the [iCORE](https://www.youtube.com/watch?v=OpRA_1kvCQE) Lab under the supervision of Dr. [Corina Barbalata](https://www.lsu.edu/eng/mie/people/faculty/barbalata.php) in 
  the Louisiana State University. My reserach focuses on developing novel sparse-metric-semantic Visual SLAM frameworks for collaborative robots working in GPS-deined cluttured indoor environments.
  Before joining LSU, I completed my master's degree at the [University of Louisiana at Lafayette](https://grail.cs.washington.edu/) in 2021 where I was advised by
  Dr. [Raju Gottumukkala](https://mechanical.louisiana.edu/node/165). There, I developed an innovative multi-user indoor positioning system using computer vision and deep learning which has recently been submitted for a [patent](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=ghOa1ZkAAAAJ&citation_for_view=ghOa1ZkAAAAJ:LkGwnXOMwfcC).
  My researh interests lies in Visual SLAM, navigation and predictive control. Through various funded projects, I have had the opportunity to work with industrial-grade mobile manipulators, UGVs and Mars rover in simulated enviornments, a diverse range of RGB-D sensors, object detection, 6D Pose Estimation, and VSLAM frameworks.
  Alongsde my core reserach,  I developed strong hands-on skill in Optimization, Neural network design with PyTorch, Git, ROS (1 and 2), CI/CD with Docker, and physics-based
  simulation using (Gazebo and O3DE). I am actively engaged with the open-source community having contributed in multiple influential projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mechazo11.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: _
github_username: Mechazo11
google_scholar: ghOa1ZkAAAAJ&hl
google_analytics: _

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
